### ISSUE TITLE
Unexpected end of JSON input when running `standard-version`.

### ISSUE THREAD

**Issue by joshtoper** [conventional-changelog/standard-version#535]
I'm using the latest version of the project, installed globally (although installing locally produces the same results). When running the `standard-version` command, I get this:

```
xxx in /Library/WebServer/Documents/xxx/xxx on branch sv > standard-version
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at module.exports.getConfiguration (/usr/local/lib/node_modules/standard-version/lib/configuration.js:25:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/standard-version/command.js:116:11)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/standard-version/bin/cli.js:8:21)
```
I've used the Standard Version successfully in another project. These are both Ruby on Rails websites; the only difference is that the one I'm having trouble with has a `package.json` file, whereas the project on which it runs without issue does not.

Here is the `package.json` file for the problem project, if it helps:

```
{
  "name": "paid_service",
  "private": true,
  "dependencies": {
    "@babel/polyfill": "^7.0.0-rc.1",
    "@babel/preset-env": "^7.0.0-rc.1",
    "@rails/webpacker": "^3.0.2",
    "@testing-library/react": "^8.0.1",
    "airbrake-js": "^2.0.0-beta",
    "babel-preset-react": "^6.24.1",
    "coffeescript": "1.12.7",
    "cross-fetch": "^3.0.4",
    "i18n-js": "^3.0.11",
    "json-loader": "^0.5.7",
    "moment": "^2.22.2",
    "node-fetch": "^2.6.0",
    "polished": "^3.4.0",
    "prop-types": "^15.6.2",
    "react": "^16.8.0",
    "react-addons-test-utils": "^15.6.2",
    "react-datepicker": "1.5.0",
    "react-dom": "^16.5.2",
    "react-hot-loader": "4",
    "react-redux": "^6.0.0",
    "react-select": "^3.0.4",
    "react-slick": "^0.24.0",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-promise-middleware": "^6.0.1",
    "redux-thunk": "^2.3.0",
    "styled-components": "^4.3.2",
    "webpack-merge": "^4.1.0",
    "webpacker-react": "^0.3.2",
    "whatwg-fetch": "^3.0.0",
    "yaml-loader": "^0.5.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "babel-jest": "^23.6.0",
    "babel-preset-env": "^1.7.0",
    "browser-sync": "^2.18.13",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.6.0",
    "eslint": "4.19.1",
    "eslint-config-prettier": "^4.3.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.13.0",
    "eslint-plugin-react-hooks": "^1.6.0",
    "jest": "^23.6.0",
    "jest-enzyme": "^7.0.0",
    "prettier": "^1.17.1",
    "react-test-renderer": "^16.8.6",
    "webpack-dashboard": "^1.0.0",
    "webpack-dev-server": "^2.9.2"
  },
  "scripts": {
    "test": "jest --passWithNoTests",
    "test-watch": "jest --watch",
    "eslint": "./node_modules/.bin/eslint . --ext .js,.jsx --ignore-path .gitignore",
    "lint": "yarn eslint --quiet & rubocop -a"
  },
  "jest": {
    "roots": [
      "spec/javascript",
      "app/javascript/packs"
    ],
    "moduleDirectories": [
      "app/javascript/packs",
      "app/javascript/src",
      "node_modules"
    ],
    "setupTestFrameworkScriptFile": "./node_modules/jest-enzyme/lib/index.js",
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/spec/react/__mocks__/imageMock.js",
      "\\.(css|less)$": "<rootDir>/spec/react/__mocks__/styleMock.js"
    }
  }
}
```

I've tried updating dependencies, re-installing node, every method of invocating the command and still I get this. I have not added any custom configuration, and I'm frankly a bit stuck so any help would be greatly appreciated.

**Comment by joshtoper** [comment]
I'm an idiot.
